version: '3'

services: 

  app:
    build:
      context: ./node
    container_name: app
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - nginx-challenge

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-challenge

  nginx:
    build: 
      context: ./nginx
    container_name: nginx        
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app
    networks: 
      - nginx-challenge

networks:
  nginx-challenge:
    driver: bridge